# syntax=docker/dockerfile:1.7
#--stage build--
FROM node:20-alpine AS build

#--env variables--
ENV PNPM_HOME=/pnpm     PATH=/pnpm:$PATH     NODE_ENV=production

#--install dependencies--
RUN apk add --no-cache ffmpeg dumb-init   && corepack enable   && corepack prepare pnpm@10.12.1 --activate

#--working directory--
WORKDIR /app

#--copy package files--
COPY package.json pnpm-lock.yaml ./

#--install dependencies--
RUN --mount=type=cache,id=backend-pnpm,target=/pnpm/store     pnpm install --frozen-lockfile --prod

#--copy source code--
COPY src ./src
COPY public ./public

#--create directories--
RUN mkdir -p public/temp public/chunkPlaylist   && chown -R node:node /app

#--stage runtime--
FROM node:20-alpine AS runtime

#--env variables--
ENV NODE_ENV=production     PORT=8080

#--install dependencies--
RUN apk add --no-cache ffmpeg dumb-init

#--working directory--
WORKDIR /app

#--copy files from build stage--
COPY --from=build --chown=node:node /app/package.json ./package.json
COPY --from=build --chown=node:node /app/node_modules ./node_modules
COPY --from=build --chown=node:node /app/src ./src
COPY --from=build --chown=node:node /app/public ./public

#--run user--
USER node

#--expose port--
EXPOSE 8080

#--entry point--
ENTRYPOINT ["dumb-init", "--"]
#--command--
CMD ["node", "-r", "dotenv/config", "--experimental-json-modules", "src/index.js"]
